language: perl
dist: xenial
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
matrix:
  include:
    # use trusty because xenial doesn't support 5.20
    - perl: "5.20"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.14"
      dist: trusty
    - perl: "5.12"
      dist: trusty
    - perl: "5.10"
      dist: trusty
env:
  - REDIS_BACKEND=Redis
  - REDIS_BACKEND=Redis::Fast
install:
  - cpanm --quiet --installdeps --notest .
  - cpanm --quiet --notest $REDIS_BACKEND
