name: "test"
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: list
        id: set-matrix
        run: |
          import json
          import os
          perl = [
              # the latest supported version
              '5.44',
              '5.42',

              # the oldest supported version
              '5.10'
          ]
          redis = [
              '8.10',
              '8.8',
              '8.6',
              '8.4',
              '8.2',
              '8.0',
              '7.4',
              '7.2',
              '6.2',
          ]
          backend = [
              'Redis',
              'Redis::Fast',
          ]
          includes = []
          for r in redis:
              for b in backend:
                  includes.append({
                      'perl': perl[0],
                      'redis': r,
                      'os': 'macos-latest',
                      'backend': b,
                  })
          matrix = {
              'perl': perl,
              'redis': redis,
              'os': ['ubuntu-latest'],
              'backend': backend,
              'include': includes
          }
          output = json.dumps(matrix, separators=(',', ':'))
          with open(os.environ["GITHUB_OUTPUT"], 'a', encoding="utf-8") as f:
            f.write('matrix={0}\n'.format(output))
        shell: python

  test:
    runs-on: ${{ matrix.os }}
    needs: list

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@3d3cb73ca65d657a809d97eab324d4e4f140bf5e # v1.42.0
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          install-modules-args: --with-develop
          install-modules: |
            Minilla
            Redis
            Redis::Fast
      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@59cda539fd5cc9be4c42bb07e4b28156951f37d6 # v1.55.0
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: false

      - name: Test
        run: |
          minil test
        env:
          REDIS_BACKEND: ${{ matrix.backend }}
