name: "test"
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: list
        id: set-matrix
        run: |
          import json
          import os
          perl = [
              # the latest supported version
              '5.44',
              '5.42',

              # the oldest supported version
              '5.24'
          ]
          redis = [
              '8.10',
              '8.8',
              '8.6',
              '8.4',
              '8.2',
              '8.0',
              '7.4',
              '7.2',
              '6.2',

              # Valkey versions
              'valkey-9.1',
              'valkey-9.0',
              'valkey-8.1',
              'valkey-8.0',
              'valkey-7.2',
          ]
          backend = [
              'Redis',
              'Redis::Fast',
          ]
          includes = []
          for r in redis:
              includes.append({
                  'perl': perl[0],
                  'redis': r,
                  'os': 'macos-latest',
                  'backend': 'Redis',
              })
          matrix = {
              'perl': perl,
              'redis': redis,
              'os': ['ubuntu-latest'],
              'backend': backend,
              'include': includes
          }
          output = json.dumps(matrix, separators=(',', ':'))
          with open(os.environ["GITHUB_OUTPUT"], 'a', encoding="utf-8") as f:
            f.write('matrix={0}\n'.format(output))
        shell: python

  test:
    runs-on: ${{ matrix.os }}
    needs: list

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@53e33bb27be492a926eee378e8a5f7ff6618b061 # v1.43.1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpm
          install-modules-args: --with-develop
          install-modules: |
            Minilla
            ${{ matrix.backend }}
      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@88a1fb308aae95aa485bf3da667c9d6e61be4c53 # v1.58.0
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: false

      - name: Test
        run: |
          minil test
        env:
          REDIS_BACKEND: ${{ matrix.backend }}
